# Generated by Django 2.2.6 on 2019-10-20 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('desc', models.TextField()),
                ('is_accepting_donations', models.PositiveSmallIntegerField()),
                ('requirement', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp_date', models.DateTimeField()),
                ('will_handle_delivery', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('rec_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodhacks.Source')),
            ],
        ),
    ]
