# Generated by Django 2.2.6 on 2019-10-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
