# Generated by Django 2.2.6 on 2019-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='source_restaurant',
            field=models.CharField(max_length=20),
        ),
    ]
